### ISSUE TITLE
cmake doesn't work (Linux)

### ISSUE THREAD

**Issue by SimonMaracine** [Dementor100/freetype-jni#2]
First, cmake immediately throws an error:

"CMake_ Error at CMakeLists.txt:9 (add_subdirectory):
  The source directory

    /home/simon/Desktop/freetype-jni-master/freetype2

  does not contain a CMakeLists.txt file."

And even with the line 9 commented out, I can't seem to successfully build it.

**Comment by mlomb** [comment]
Make sure you cloned the repository using the `--recursive` flag like so:

> git clone https://github.com/mlomb/freetype-jni.git --recursive

If you don't want to clone again you can also update the submodules like so:
> git submodule init
> git submodule update

**Comment by SimonMaracine** [comment]
Ok. I downloaded the .zip and that's why freetype2 was missing, but now it doesn't link:

"/usr/bin/ld: freetype2/libfreetype.a(ftbase.c.o): relocation R_X86_64_PC32 against symbol `FT_MulDiv' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
..."

I'm sorry, but I'm not an expert in CMake and I don't understand what to do.
And thank you for responding!

**Comment by mlomb** [comment]
Try adding

> set(CMAKE_POSITION_INDEPENDENT_CODE ON)

to CMakeLists.txt, delete the old build and run again.
This should enable the `-fPIC` flag.

**Comment by SimonMaracine** [comment]
Yes, now it builds successfully. Thank you!
